server {
    listen 80 default_server;
    server_name _;
    root /var/www/event;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }

    # Kacheln & Bilder lang cachen
    location ~* \.(png|jpg|jpeg|webp)$ {
        expires 30d;
        access_log off;
    }

    # Service Worker selbst nie langfristig cachen, sonst kommen Updates nicht an
    location = /sw.js {
        add_header Cache-Control "no-cache";
    }
}
